services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - BOT_ROLE=app
    ports:
      - '3011:3010'
    depends_on:
      - postgres
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 3010

  worker:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - BOT_ROLE=worker
    depends_on:
      - postgres
      - redis
    command: arq app.worker.WorkerSettings

  bot:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - BOT_ROLE=app
    depends_on:
      - postgres
      - redis
    command: python -m app.bot_runner

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=tgbot
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6381:6379'

volumes:
  postgres_data:
